# Generated by Django 4.0 on 2021-12-24 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Business', 'Business'), ('Stocks', 'Stocks'), ('Communication', 'Communication'), ('Real Estate', 'Real Estate'), ('Code', 'Code'), ('Misc', 'Misc')], default='Misc', max_length=50)),
                ('chapter', models.IntegerField(default=0)),
                ('chapter_title', models.CharField(max_length=200)),
                ('sub_chapter', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('excerpt', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
